console.log("Hello".at(-4));
console.log("Hello".charAt(4));
console.log("Hello".concat(" ","World"));
console.log("Hello".startsWith("H"));
console.log("Hello".endsWith("o"));
console.log("Hello".includes("x"));
console.log("Hello".indexOf("e"));
console.log("Hello".lastIndexOf("l"));
console.log("Hello".match(/[A-Z]/g));
console.log("Hello".padStart(6,"?"));
console.log("Hello".padEnd(6,"?"));
console.log("Hello".repeat(4));
console.log("Hello".replace("llo","y"));
console.log("Hello".search("e"));
console.log("Hello".slice(1,3));
console.log("Hello".split(""));
console.log("Hello".substring(2,4));
console.log("Hello".toLowerCase());
console.log("Hello".toUpperCase());
console.log(" Hello ".trim());
console.log(" Hello ".trimStart());
console.log(" Hello ".trimEnd());